// <auto-generated />
using System;
using EpicTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EpicTracker.Migrations
{
    [DbContext(typeof(EpicTrackerDbContext))]
    [Migration("20260604213204_RenameAssignedAgentIdToName")]
    partial class RenameAssignedAgentIdToName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EpicTracker.Data.EpicAuditEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentSwarm")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicAgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicAgentInstruction")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanInLoop")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpicId");

                    b.ToTable("EpicAudits");
                });

            modelBuilder.Entity("EpicTracker.Data.EpicEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentSwarm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brief")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodingAgentNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicAgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanInLoop")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDocDrafted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMockupDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsMockup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewerAgentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Epics");
                });

            modelBuilder.Entity("EpicTracker.Data.SpecEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentSwarm")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CodeReviewRequired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicAgentInstruction")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanInLoop")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAbandoned")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsAcPassed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCodeDone")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsCodeReviewApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadyToCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpecApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpecDrafted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewerAgentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecDocPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpicId");

                    b.ToTable("Specs");
                });

            modelBuilder.Entity("EpicTracker.Data.EpicAuditEntity", b =>
                {
                    b.HasOne("EpicTracker.Data.EpicEntity", "Epic")
                        .WithMany("Audits")
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epic");
                });

            modelBuilder.Entity("EpicTracker.Data.SpecEntity", b =>
                {
                    b.HasOne("EpicTracker.Data.EpicEntity", "Epic")
                        .WithMany("Specs")
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epic");
                });

            modelBuilder.Entity("EpicTracker.Data.EpicEntity", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Specs");
                });
#pragma warning restore 612, 618
        }
    }
}
