// <auto-generated />
using System;
using EpicTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EpicTracker.Migrations
{
    [DbContext(typeof(EpicTrackerDbContext))]
    [Migration("20260612233110_AddSpecName")]
    partial class AddSpecName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EpicTracker.Data.AuditLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecState")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpicId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EpicTracker.Data.EpicEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentSwarm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brief")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodingAgentNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicAgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanInLoop")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsACRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBriefRefined")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCodeReviewRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDocDrafted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMockupDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastKnownStateName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsMockup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewerAgentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WaterproofingIterations")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Epics");
                });

            modelBuilder.Entity("EpicTracker.Data.SpecEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentSwarm")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeReviewIterations")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DependsOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicAgentInstruction")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanInLoop")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsACRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAbandoned")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsAcPassed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCodeDone")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsCodeReviewApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsCodeReviewRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadyToCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpecApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpecDrafted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastKnownStateName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRejectionNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerAgentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeChange")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecDocPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpicId");

                    b.ToTable("Specs");
                });

            modelBuilder.Entity("EpicTracker.Data.AuditLogEntity", b =>
                {
                    b.HasOne("EpicTracker.Data.EpicEntity", "Epic")
                        .WithMany("AuditLogs")
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epic");
                });

            modelBuilder.Entity("EpicTracker.Data.SpecEntity", b =>
                {
                    b.HasOne("EpicTracker.Data.EpicEntity", "Epic")
                        .WithMany("Specs")
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epic");
                });

            modelBuilder.Entity("EpicTracker.Data.EpicEntity", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Specs");
                });
#pragma warning restore 612, 618
        }
    }
}
